// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../discovery/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelTransfer(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(900002248, transferID);
}

export function GetPort(): $CancellablePromise<number> {
    return $Call.ByID(4195335736);
}

export function GetTransfer(transferID: string): $CancellablePromise<[$models.Transfer, boolean]> {
    return $Call.ByID(1198637268, transferID).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

export function GetTransferList(): $CancellablePromise<$models.Transfer[]> {
    return $Call.ByID(584162076).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolvePendingRequest 外部调用，解决待处理的传输请求
 * 返回 true 表示成功处理，false 表示未找到该 ID 的请求
 */
export function ResolvePendingRequest(id: string, accept: boolean, savePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(207902967, id, accept, savePath);
}

export function SendFile(target: discovery$0.Peer | null, targetIP: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2954589433, target, targetIP, filePath);
}

export function SendFolder(target: discovery$0.Peer | null, targetIP: string, folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3258308403, target, targetIP, folderPath);
}

export function SendText(target: discovery$0.Peer | null, targetIP: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1497421440, target, targetIP, text);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3611800535);
}

// Private type creation functions
const $$createType0 = $models.Transfer.createFrom;
const $$createType1 = $Create.Array($$createType0);
