/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    PeerCard: typeof import('./src/components/PeerCard.vue')['default']
    TransferItem: typeof import('./src/components/TransferItem.vue')['default']
  }
}
