//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../../../../../mesh-drop/internal/discovery/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "peers:update": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = discovery$0.Peer.createFrom;
const $$createType1 = $Create.Array($$createType0);

configure();
