// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetSavePath(): $CancellablePromise<string> {
    return $Call.ByID(4081533263);
}

/**
 * Save 保存配置到磁盘
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(3089450934);
}

/**
 * SetSavePath 修改配置
 */
export function SetSavePath(savePath: string): $CancellablePromise<void> {
    return $Call.ByID(3805718491, savePath);
}
