// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetAutoAccept(): $CancellablePromise<boolean> {
    return $Call.ByID(2605668438);
}

export function GetHostName(): $CancellablePromise<string> {
    return $Call.ByID(972342140);
}

export function GetID(): $CancellablePromise<string> {
    return $Call.ByID(4240411568);
}

export function GetSaveHistory(): $CancellablePromise<boolean> {
    return $Call.ByID(2178923392);
}

export function GetSavePath(): $CancellablePromise<string> {
    return $Call.ByID(4081533263);
}

/**
 * Save 保存配置到磁盘
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(3089450934);
}

export function SetAutoAccept(autoAccept: boolean): $CancellablePromise<void> {
    return $Call.ByID(3371961138, autoAccept);
}

export function SetHostName(hostName: string): $CancellablePromise<void> {
    return $Call.ByID(1580131496, hostName);
}

export function SetSaveHistory(saveHistory: boolean): $CancellablePromise<void> {
    return $Call.ByID(3779587628, saveHistory);
}

/**
 * SetSavePath 修改配置
 */
export function SetSavePath(savePath: string): $CancellablePromise<void> {
    return $Call.ByID(3805718491, savePath);
}
