// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetID(): $CancellablePromise<string> {
    return $Call.ByID(1539451205);
}

export function GetPeerByIP(ip: string): $CancellablePromise<$models.Peer | null> {
    return $Call.ByID(1626825408, ip).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPeers(): $CancellablePromise<$models.Peer[]> {
    return $Call.ByID(3041084029).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1014177536);
}

// Private type creation functions
const $$createType0 = $models.Peer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
